// GET ALL ITEMS REQ
export const GET_ALL_ITEMS_REQ = "GET_ALL_ITEMS_REQ";

export const GET_ALL_ITEMS_SUCESS = "GET_ALL_ITEMS_SUCESS";

export const GET_ALL_ITEMS_FAILED = "GET_ALL_ITEMS_FAILED";

export const RESET_ALL_ITEM_REDUX = "RESET_ALL_ITEM_REDUX";


// GET ALL ITEMS REQ
export const GET_ITEMS_BY_ID_REQ = "GET_ITEMS_BY_ID_REQ";

export const GET_ITEMS_BY_ID_SUCESS = "GET_ITEMS_BY_ID_SUCESS";

export const GET_ITEMS_BY_ID_FAILED = "GET_ITEMS_BY_ID_FAILED";

export const RESET_ITEM_ID_REDUX = "RESET_ITEM_ID_REDUX";


//UPDATE ITEM
export const UPDATE_ITEM_REQ = "UPDATE_ITEM_REQ";

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";

export const UPDATE_ITEM_FAILED = "UPDATE_ITEM_FAILED";




//DELETE ITEM
export const DELETE_ITEM_REQ = "DELETE_ITEM_REQ";

export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";

export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED";

export const RESET_DELETE_ITEM_REDUX = "RESET_DELETE_ITEM_REDUX";
